name: simple_movie_app
description: A new Flutter Challenge project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.2
  
  
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dartz: ^0.10.1
  freezed: ^2.2.1
  freezed_annotation: ^2.1.0
  build_runner: ^2.3.2
  flutter_bloc: ^8.1.1
  eva_icons_flutter: ^3.1.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:

  uses-material-design: true

